### ISSUE TITLE
Сделать таблицу рисков

### ISSUE THREAD

**Issue by aavortep** [aavortep/bmstu_team_development#10]
Таблица должна состоять из следующих колонок:
- приоритет (целое число)
- формулировка риска
- состояние (анализ/мониторинг/реакция/закрыт)
- вероятность срабатывания риска (высокая/средняя/низкая)
- урон (катастрофический/высокий/средний)
- воздействие (катастрофическое/высокое/среднее) (определяется по таблице из презентации)
- тип стратегии (уклонение/принятие/передача/снижение)
- описание стратегии
- ФИО ответственного
- комментарии к закрытию (описывается после перевода риска в состояние "закрыт")

Таблицу залить в wiki на отдельную страницу.
Ссылку прикрепить здесь в комментариях и отметить меня.

**Comment by IThror10** [comment]
@aavortep 
Инициализирована [таблица рисков](https://github.com/aavortep/bmstu_team_development/wiki/Управление-рисками/431ada08ea416fe31a68a2ca3a87c39a811833b2) на отдельной [wiki](https://github.com/aavortep/bmstu_team_development/wiki/Управление-рисками) странице.
Переназначить ответственных за риски при необходимости.

Предполагается, что риск <<Неверной Оценки Размеров Разрабатываемой системы>> будет закрыт после создания Диаграммы Классов.

**Comment by aavortep** [comment]
> @aavortep Инициализирована [таблица рисков](https://github.com/aavortep/bmstu_team_development/wiki/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B8%D1%81%D0%BA%D0%B0%D0%BC%D0%B8/431ada08ea416fe31a68a2ca3a87c39a811833b2) на отдельной [wiki](https://github.com/aavortep/bmstu_team_development/wiki/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B8%D1%81%D0%BA%D0%B0%D0%BC%D0%B8) странице. Переназначить ответственных за риски при необходимости.
> 
> Предполагается, что риск <<Неверной Оценки Размеров Разрабатываемой системы>> будет закрыт после создания Диаграммы Классов.

В некоторых местах добавила ответственных. В остальном в принципе вопросов нет
